/*
 * esa API
 *
 * API reference for selected endpoints from esa.io.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};

/// struct for passing parameters to the method `v1_teams_team_name_posts_get`
#[derive(Clone, Debug)]
pub struct V1TeamsTeamNamePostsGetParams {
    pub team_name: String,
    /// Filter condition for posts.
    pub q: Option<String>,
    /// Include related resources (comments, comments.stargazers, stargazers).
    pub include: Option<String>,
    /// Sort key.
    pub sort: Option<String>,
    /// Sort order.
    pub order: Option<String>
}

/// struct for passing parameters to the method `v1_teams_team_name_posts_post_number_get`
#[derive(Clone, Debug)]
pub struct V1TeamsTeamNamePostsPostNumberGetParams {
    pub team_name: String,
    pub post_number: i32,
    /// Include related resources (comments, comments.stargazers, stargazers).
    pub include: Option<String>
}

/// struct for passing parameters to the method `v1_user_get`
#[derive(Clone, Debug)]
pub struct V1UserGetParams {
    /// Include related resources. Use \"teams\" to include the teams array.
    pub include: Option<String>
}


/// struct for typed errors of method `v1_teams_team_name_posts_get`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1TeamsTeamNamePostsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method `v1_teams_team_name_posts_post_number_get`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1TeamsTeamNamePostsPostNumberGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method `v1_user_get`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1UserGetError {
    UnknownValue(serde_json::Value),
}


/// Returns a list of posts.
pub async fn v1_teams_team_name_posts_get(configuration: &configuration::Configuration, params: V1TeamsTeamNamePostsGetParams) -> Result<crate::models::PostListResponse, Error<V1TeamsTeamNamePostsGetError>> {
    // unbox the parameters
    let team_name = params.team_name;
    let q = params.q;
    let include = params.include;
    let sort = params.sort;
    let order = params.order;


    let local_var_client = &configuration.client;

    let local_var_uri_str = format!("{}/v1/teams/{team_name}/posts", configuration.base_path, team_name=crate::apis::urlencode(team_name));
    let mut local_var_req_builder = local_var_client.get(local_var_uri_str.as_str());

    if let Some(ref local_var_str) = q {
        local_var_req_builder = local_var_req_builder.query(&[("q", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = include {
        local_var_req_builder = local_var_req_builder.query(&[("include", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = sort {
        local_var_req_builder = local_var_req_builder.query(&[("sort", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = order {
        local_var_req_builder = local_var_req_builder.query(&[("order", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_apikey) = configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.query(&[("access_token", local_var_value)]);
    }
    if let Some(ref local_var_user_agent) = configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<V1TeamsTeamNamePostsGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns the specified post.
pub async fn v1_teams_team_name_posts_post_number_get(configuration: &configuration::Configuration, params: V1TeamsTeamNamePostsPostNumberGetParams) -> Result<crate::models::Post, Error<V1TeamsTeamNamePostsPostNumberGetError>> {
    // unbox the parameters
    let team_name = params.team_name;
    let post_number = params.post_number;
    let include = params.include;


    let local_var_client = &configuration.client;

    let local_var_uri_str = format!("{}/v1/teams/{team_name}/posts/{post_number}", configuration.base_path, team_name=crate::apis::urlencode(team_name), post_number=post_number);
    let mut local_var_req_builder = local_var_client.get(local_var_uri_str.as_str());

    if let Some(ref local_var_str) = include {
        local_var_req_builder = local_var_req_builder.query(&[("include", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_apikey) = configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.query(&[("access_token", local_var_value)]);
    }
    if let Some(ref local_var_user_agent) = configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<V1TeamsTeamNamePostsPostNumberGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns the user associated with the access token.
pub async fn v1_user_get(configuration: &configuration::Configuration, params: V1UserGetParams) -> Result<crate::models::User, Error<V1UserGetError>> {
    // unbox the parameters
    let include = params.include;


    let local_var_client = &configuration.client;

    let local_var_uri_str = format!("{}/v1/user", configuration.base_path);
    let mut local_var_req_builder = local_var_client.get(local_var_uri_str.as_str());

    if let Some(ref local_var_str) = include {
        local_var_req_builder = local_var_req_builder.query(&[("include", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_apikey) = configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.query(&[("access_token", local_var_value)]);
    }
    if let Some(ref local_var_user_agent) = configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<V1UserGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

