/*
 * esa API
 *
 * API reference for selected endpoints from esa.io.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostListResponse {
    #[serde(rename = "posts", skip_serializing_if = "Option::is_none")]
    pub posts: Option<Vec<crate::models::Post>>,
    #[serde(rename = "prev_page", skip_serializing_if = "Option::is_none")]
    pub prev_page: Option<i32>,
    #[serde(rename = "next_page", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<i32>,
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "per_page", skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i32>,
    #[serde(rename = "max_per_page", skip_serializing_if = "Option::is_none")]
    pub max_per_page: Option<i32>,
}

impl PostListResponse {
    pub fn new() -> PostListResponse {
        PostListResponse {
            posts: None,
            prev_page: None,
            next_page: None,
            total_count: None,
            page: None,
            per_page: None,
            max_per_page: None,
        }
    }
}


