/*
 * esa API
 *
 * API reference for selected endpoints from esa.io.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Post {
    /// Post number within the team.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "wip", skip_serializing_if = "Option::is_none")]
    pub wip: Option<bool>,
    #[serde(rename = "body_md", skip_serializing_if = "Option::is_none")]
    pub body_md: Option<String>,
    #[serde(rename = "body_html", skip_serializing_if = "Option::is_none")]
    pub body_html: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "revision_number", skip_serializing_if = "Option::is_none")]
    pub revision_number: Option<i32>,
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<crate::models::UserSummary>>,
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Box<crate::models::UserSummary>>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Kind>,
    #[serde(rename = "comments_count", skip_serializing_if = "Option::is_none")]
    pub comments_count: Option<i32>,
    #[serde(rename = "tasks_count", skip_serializing_if = "Option::is_none")]
    pub tasks_count: Option<i32>,
    #[serde(rename = "done_tasks_count", skip_serializing_if = "Option::is_none")]
    pub done_tasks_count: Option<i32>,
    #[serde(rename = "stargazers_count", skip_serializing_if = "Option::is_none")]
    pub stargazers_count: Option<i32>,
    #[serde(rename = "watchers_count", skip_serializing_if = "Option::is_none")]
    pub watchers_count: Option<i32>,
    #[serde(rename = "star", skip_serializing_if = "Option::is_none")]
    pub star: Option<bool>,
    #[serde(rename = "watch", skip_serializing_if = "Option::is_none")]
    pub watch: Option<bool>,
}

impl Post {
    pub fn new() -> Post {
        Post {
            number: None,
            name: None,
            full_name: None,
            wip: None,
            body_md: None,
            body_html: None,
            created_at: None,
            updated_at: None,
            message: None,
            url: None,
            tags: None,
            category: None,
            revision_number: None,
            created_by: None,
            updated_by: None,
            kind: None,
            comments_count: None,
            tasks_count: None,
            done_tasks_count: None,
            stargazers_count: None,
            watchers_count: None,
            star: None,
            watch: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "stock")]
    Stock,
    #[serde(rename = "flow")]
    Flow,
}

