/*
 * esa API
 *
 * API reference for selected endpoints from esa.io.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSummary {
    #[serde(rename = "myself", skip_serializing_if = "Option::is_none")]
    pub myself: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "screen_name", skip_serializing_if = "Option::is_none")]
    pub screen_name: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
}

impl UserSummary {
    pub fn new() -> UserSummary {
        UserSummary {
            myself: None,
            name: None,
            screen_name: None,
            icon: None,
        }
    }
}


